### PR TITLE
Revert "Use Jammy for all builds"

### PR DESCRIPTION
**Pull request by MonicaisHer**

### CODE REVIEW

**Comment by farshidtz** [comment]
I just remembered why I set Jammy for all: device-gpio call wasn't getting the series value from the matrix and not falling back to the action's default either. This is because an empty string is passed to the action and default isn't used; see https://github.com/actions/runner/issues/924#issuecomment-1050951162.

Build log: https://github.com/canonical/edgex-nightly-build/runs/7295965153?check_suite_focus=true#step:2:75

**Comment by MonicaisHer** [comment]
> I just remembered why I set Jammy for all. Because device-gpio call wasn't getting the series value from the matrix: https://github.com/canonical/edgex-nightly-build/runs/7295965153?check_suite_focus=true#step:2:75

could we add `ubuntu_series: focal` for device-gpio?
```
- snap: edgex-device-gpio
  arch: armhf
  ubuntu_series: focal
```

**Comment by farshidtz** [comment]
> > I just remembered why I set Jammy for all. Because device-gpio call wasn't getting the series value from the matrix: https://github.com/canonical/edgex-nightly-build/runs/7295965153?check_suite_focus=true#step:2:75
> 
> could we add `ubuntu_series: focal` for device-gpio?
> 
> ```
> - snap: edgex-device-gpio
>   arch: armhf
>   ubuntu_series: focal
> ```

Ya that should solve it. Or we change the action to default to focal when the input is empty. We can then remove some complexity here.

**Comment by MonicaisHer** [comment]
> > > I just remembered why I set Jammy for all. Because device-gpio call wasn't getting the series value from the matrix: https://github.com/canonical/edgex-nightly-build/runs/7295965153?check_suite_focus=true#step:2:75
> > 
> > 
> > could we add `ubuntu_series: focal` for device-gpio?
> > ```
> > - snap: edgex-device-gpio
> >   arch: armhf
> >   ubuntu_series: focal
> > ```
> 
> Ya that should solve it. Or we change the action to default to focal when the input is empty. We can then remove some complexity here.

The default is focal already: 
https://github.com/canonical/edgex-launchpad-build-action/blob/16e23cf21ddc03680412eb3b9ed6de946e23a2ac/action.yml#L19-L22

**Comment by farshidtz** [comment]
> The default is focal already: https://github.com/canonical/edgex-launchpad-build-action/blob/16e23cf21ddc03680412eb3b9ed6de946e23a2ac/action.yml#L19-L22

I've updated my comment and explained why that doesn't work: https://github.com/canonical/edgex-nightly-build/pull/26#issuecomment-1182999963

**Review by farshidtz — APPROVED** [review]

**Pull request merged**
